const fs = require("fs");
const path = require("path");
const {
  withAppBuildGradle,
  withMainApplication,
  withDangerousMod,
  withGradleProperties,
} = require("@expo/config-plugins");

/**
 * Expo config plugin for the Janam hardware imager (XT40 and other Janam terminals).
 *
 * The android/ directory is regenerated by `expo prebuild` (and on every EAS build), so the
 * native scanning code can't just live there. This plugin re-injects it from the tracked
 * `native/janam/` folder on each prebuild:
 *   1. copies the Janam SDK jar into android/app/libs
 *   2. copies the vendored SDK support sources + the RN bridge module into the app source tree
 *   3. adds the jar as a gradle dependency
 *   4. registers JanamScannerPackage in MainApplication
 *
 * See src/janamScanner.ts (JS side) and native/janam/ (native source of truth).
 */

const JAR_NAME = "janam.device.sdk-4.0.5.jar";
const GRADLE_DEP = `implementation(files("libs/${JAR_NAME}"))`;
const GRADLE_ANCHOR = `implementation("com.facebook.react:react-android")`;
const PACKAGE_REGISTER = "add(JanamScannerPackage())";
const PACKAGE_ANCHOR = "PackageList(this).packages.apply {";

function copyDirRecursive(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const from = path.join(src, entry.name);
    const to = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDirRecursive(from, to);
    else fs.copyFileSync(from, to);
  }
}

// 1 + 2: copy the jar and native sources into the freshly-generated android project.
const withJanamNativeFiles = (config) =>
  withDangerousMod(config, [
    "android",
    (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const androidAppDir = path.join(
        config.modRequest.platformProjectRoot,
        "app"
      );
      const source = path.join(projectRoot, "native", "janam");

      // jar -> android/app/libs
      const libsDest = path.join(androidAppDir, "libs");
      fs.mkdirSync(libsDest, { recursive: true });
      fs.copyFileSync(
        path.join(source, "libs", JAR_NAME),
        path.join(libsDest, JAR_NAME)
      );

      // java/kotlin sources -> android/app/src/main/java
      copyDirRecursive(
        path.join(source, "java"),
        path.join(androidAppDir, "src", "main", "java")
      );

      return config;
    },
  ]);

// 3: add the jar as a gradle dependency (idempotent).
const withJanamGradleDep = (config) =>
  withAppBuildGradle(config, (config) => {
    let contents = config.modResults.contents;
    if (!contents.includes(GRADLE_DEP)) {
      if (contents.includes(GRADLE_ANCHOR)) {
        contents = contents.replace(
          GRADLE_ANCHOR,
          `${GRADLE_ANCHOR}\n\n    // Janam device scanning SDK — drives the XT40 hardware imager.\n    ${GRADLE_DEP}`
        );
      } else {
        // Fallback: append to the dependencies block.
        contents = contents.replace(
          /dependencies\s*{/,
          `dependencies {\n    ${GRADLE_DEP}`
        );
      }
      config.modResults.contents = contents;
    }
    return config;
  });

// 4: register the package in MainApplication (idempotent).
const withJanamPackage = (config) =>
  withMainApplication(config, (config) => {
    let contents = config.modResults.contents;
    if (!contents.includes(PACKAGE_REGISTER)) {
      contents = contents.replace(
        PACKAGE_ANCHOR,
        `${PACKAGE_ANCHOR}\n              ${PACKAGE_REGISTER}`
      );
      config.modResults.contents = contents;
    }
    return config;
  });

// Restrict native builds to ARM ABIs. The app only ever runs on Janam ARM hardware (XT40 etc.),
// and the local NDK/CMake toolchain fails to configure the x86 ABI for RN's New Architecture
// C++ build. Dropping x86/x86_64 sidesteps that and shrinks the APK. Trade-off: no x86 emulator.
const withArmOnlyAbis = (config) =>
  withGradleProperties(config, (config) => {
    const KEY = "reactNativeArchitectures";
    const VALUE = "armeabi-v7a,arm64-v8a";
    const existing = config.modResults.find(
      (item) => item.type === "property" && item.key === KEY
    );
    if (existing) existing.value = VALUE;
    else config.modResults.push({ type: "property", key: KEY, value: VALUE });
    return config;
  });

module.exports = function withJanamScanner(config) {
  config = withJanamNativeFiles(config);
  config = withJanamGradleDep(config);
  config = withJanamPackage(config);
  config = withArmOnlyAbis(config);
  return config;
};
